#!/bin/sh
#
# Run each of the asm tests on the FPGA and report their output.
# You should run this from the fpga directory with the testbench
# already built and the FPGA already programmed.

for x in ../data/smips*.S.vmh
do
    echo -n $x...
    ./tb $x | grep \*
done

