#!/bin/sh
#
# Run each of the asm tests in simulation and report their output.
# You should run this from the sim directory with the dut and testbench
# already built.

# By default we use bsim_dut as the simulation. This can be overridden by
# specifying simulation executable as the first command line argument.
dut=${1:-bsim_dut}

for x in ../data/smips*.S.vmh
do
    ./$dut > out.txt 2> err.txt&
    echo -n $x...
    sleep 3
    ./tb $x | grep \*
    sleep 1
done

